/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainhub.forestapp;

import java.awt.Dimension;
import java.awt.Toolkit;

/**
 *
 * @author fred banda
 */
public class ExploreGUI extends javax.swing.JFrame {

    /**
     * Creates new form Explore
     */
    public ExploreGUI() {
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size=Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl1 = new javax.swing.JLabel();
        lbl2 = new javax.swing.JLabel();
        lbl3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA1 = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        TA2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        TA3 = new javax.swing.JTextArea();
        lbl4 = new javax.swing.JLabel();
        lbl5 = new javax.swing.JLabel();
        lbl6 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        TA4 = new javax.swing.JTextArea();
        jScrollPane5 = new javax.swing.JScrollPane();
        TA5 = new javax.swing.JTextArea();
        jScrollPane6 = new javax.swing.JScrollPane();
        TA6 = new javax.swing.JTextArea();
        Returnbtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lbl1.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/Amazon.jpeg"))); // NOI18N
        lbl1.setText("Amazon");
        getContentPane().add(lbl1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 22, -1, -1));

        lbl2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/Congo.jpeg"))); // NOI18N
        lbl2.setText("Congo Rainforest");
        getContentPane().add(lbl2, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 34, -1, -1));

        lbl3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/NG.jpeg"))); // NOI18N
        lbl3.setText("New Guinea Rainforest");
        getContentPane().add(lbl3, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 22, 479, -1));

        TA1.setColumns(20);
        TA1.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        TA1.setRows(5);
        TA1.setText("At about 2,300,000square miles in\nsize, the amazon rainforest is the the\nlarget biodiverse forest in the world.\n It Spreads across Brazil, Bolivia, Colo\nmbia, Venezuela, and the Republic \nSuriname.");
        jScrollPane1.setViewportView(TA1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 233, 322, -1));

        TA2.setColumns(20);
        TA2.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        TA2.setRows(5);
        TA2.setText("Covers over 1,400,000 square miles throu\nghout Cameroon, the Central African Republic,\nthe Republic of Congo, the Democratic Republic \nof Congo, Equatorial Guinea, and Gabon.");
        jScrollPane2.setViewportView(TA2);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(346, 217, 415, -1));

        TA3.setColumns(20);
        TA3.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        TA3.setRows(5);
        TA3.setText("The rainforests of New Guinea make\n up over half of the country’s landmass, \nincorporating vast mountainous land\nscapes spanning 303,500 square miles. \nSince it’s located on an island, the New\n Guinea rainforest is home to groups\n of Indigenous peoples and native animal\n species that have had little to no \ncontact with the outside world.");
        jScrollPane3.setViewportView(TA3);

        getContentPane().add(jScrollPane3, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 217, 406, -1));

        lbl4.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/V.jpeg"))); // NOI18N
        lbl4.setText("Valdivian Temperate Rainforest");
        getContentPane().add(lbl4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, -1, 144));

        lbl5.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/T.jpeg"))); // NOI18N
        lbl5.setText("Tongass National Forest");
        getContentPane().add(lbl5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 420, 155));

        lbl6.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/B.jpeg"))); // NOI18N
        lbl6.setText("Bosawas Biosphere Reserve");
        getContentPane().add(lbl6, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 316, 479, 184));

        TA4.setColumns(20);
        TA4.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        TA4.setRows(5);
        TA4.setText("At least 90% of the plant species that\n live inside the Valdivian temperate\n rainforest in the southern cone of \nSouth America are endemic, meaning \nthey are either native or restricted to\n that exact area.3\nAt 95,800 square miles in size, the forest \nhere also has one of the highest\n incidences of pollination performed \nby animals recorded of any temperate biome.");
        jScrollPane4.setViewportView(TA4);

        getContentPane().add(jScrollPane4, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 506, 287, 76));

        TA5.setColumns(20);
        TA5.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        TA5.setRows(5);
        TA5.setText("Found in Southeast Alaska and spanning\n about 26,560 square miles, the Tongass \nNational Forest is the largest national\n forest in the United States and the largest\n temperate rainforest in North America.\n That means it holds almost a third of \nthe Earth’s old-growth temperate rainforests,\n which are particularly important due to\n their high levels of stored carbon and biomass.");
        jScrollPane5.setViewportView(TA5);

        getContentPane().add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(463, 506, 279, 76));

        TA6.setColumns(20);
        TA6.setFont(new java.awt.Font("Times New Roman", 1, 10)); // NOI18N
        TA6.setRows(5);
        TA6.setText("Designated by UNESCO in 1997, the\n Bosawas Biosphere Reserve in Nicaragua\n covers nearly 8,500 square miles. \nIt’s estimated that about 13% of the world’s\n known species live inside the reserve,\n which is technically made up of six different\n types of forest. The reserve is also home to 20\n separate communities of Indigenous peoples\n who contribute to the protection of natural\n resources and operate their entire economies\n off the land.");
        jScrollPane6.setViewportView(TA6);

        getContentPane().add(jScrollPane6, new org.netbeans.lib.awtextra.AbsoluteConstraints(901, 506, 425, 76));

        Returnbtn.setBackground(new java.awt.Color(204, 204, 204));
        Returnbtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Returnbtn.setForeground(new java.awt.Color(255, 0, 51));
        Returnbtn.setText("Return to Menu");
        Returnbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReturnbtnActionPerformed(evt);
            }
        });
        getContentPane().add(Returnbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(571, 600, -1, 51));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/lifeonland.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 890, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ReturnbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReturnbtnActionPerformed
        // TODO add your handling code here:
        
         ForestGUI myGUI = new ForestGUI();
        myGUI.show();
        dispose();
                     
    }//GEN-LAST:event_ReturnbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ExploreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ExploreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ExploreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ExploreGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ExploreGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Returnbtn;
    private javax.swing.JTextArea TA1;
    private javax.swing.JTextArea TA2;
    private javax.swing.JTextArea TA3;
    private javax.swing.JTextArea TA4;
    private javax.swing.JTextArea TA5;
    private javax.swing.JTextArea TA6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JLabel lbl1;
    private javax.swing.JLabel lbl2;
    private javax.swing.JLabel lbl3;
    private javax.swing.JLabel lbl4;
    private javax.swing.JLabel lbl5;
    private javax.swing.JLabel lbl6;
    // End of variables declaration//GEN-END:variables
}
