/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainhub.forestapp;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Fred banda
 */
public class ForestGUI extends javax.swing.JFrame {
     ArrayList<Forest>flist;
     private String category, name,location,species,status;
     private int population, count;
     
     
   
    

    /**
     * Creates new form ForestGUI
     */
    public ForestGUI() {
        
        initComponents();
        
        Toolkit toolkit = getToolkit();
        Dimension size=Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
        
               
        flist = new ArrayList<>();
        
        
         category = new String();
         name = new String();
         location = new String();
         species = new String();
         status = new String();
         population = 0;
         count = 0;
         
              
        // show items on the form
        categoryLBL.setVisible(true);
        categoryTF.setVisible(true);
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        locationLBL.setVisible(true);
        locationTF.setVisible(true);
        speciesLBL.setVisible(true);
        speciesTF.setVisible(true);
        statusLBL.setVisible(true);
        statusTF.setVisible(true);
        populationLBL.setVisible(true);
        populationTF.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grBTN = new javax.swing.ButtonGroup();
        categoryLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        locationLBL = new javax.swing.JLabel();
        speciesLBL = new javax.swing.JLabel();
        statusLBL = new javax.swing.JLabel();
        populationLBL = new javax.swing.JLabel();
        categoryTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        locationTF = new javax.swing.JTextField();
        speciesTF = new javax.swing.JTextField();
        statusTF = new javax.swing.JTextField();
        populationTF = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        loadBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        searchBTN = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        deleteBTN = new javax.swing.JButton();
        Explorebtn = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 204, 204));
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setForeground(new java.awt.Color(204, 204, 204));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoryLBL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        categoryLBL.setText("Category");
        getContentPane().add(categoryLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 122, 70, -1));

        nameLBL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        nameLBL.setText("Name");
        getContentPane().add(nameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 154, 50, 26));

        locationLBL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        locationLBL.setText("Location");
        getContentPane().add(locationLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 191, 70, 22));

        speciesLBL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        speciesLBL.setText("species");
        getContentPane().add(speciesLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 220, 60, 28));

        statusLBL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        statusLBL.setText("Status");
        getContentPane().add(statusLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 259, 50, 23));

        populationLBL.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        populationLBL.setText("Population");
        getContentPane().add(populationLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 294, 80, 22));

        categoryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTFActionPerformed(evt);
            }
        });
        getContentPane().add(categoryTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 119, 103, -1));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 156, 103, -1));
        getContentPane().add(locationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 191, 103, -1));
        getContentPane().add(speciesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 220, 103, -1));
        getContentPane().add(statusTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 260, 103, -1));
        getContentPane().add(populationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 294, 103, -1));

        displayTA.setBackground(new java.awt.Color(204, 204, 204));
        displayTA.setColumns(20);
        displayTA.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 550, 230));

        loadBTN.setBackground(new java.awt.Color(51, 153, 0));
        loadBTN.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        loadBTN.setText("LoadFile");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });
        getContentPane().add(loadBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 120, 110, 50));

        saveBTN.setBackground(new java.awt.Color(51, 153, 0));
        saveBTN.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        saveBTN.setText("SAVE");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });
        getContentPane().add(saveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, 110, 50));

        exitBTN.setBackground(new java.awt.Color(51, 153, 0));
        exitBTN.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 110, 50));

        displayBTN.setBackground(new java.awt.Color(0, 204, 255));
        displayBTN.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(displayBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, -1, 50));

        addBTN.setBackground(new java.awt.Color(255, 0, 102));
        addBTN.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 380, 90, 50));

        searchBTN.setBackground(new java.awt.Color(51, 204, 255));
        searchBTN.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        searchBTN.setText("Search");
        searchBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBTNActionPerformed(evt);
            }
        });
        getContentPane().add(searchBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 370, -1, 50));

        jLabel1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel1.setText("        Life on Planet");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 230, 50));

        deleteBTN.setBackground(new java.awt.Color(255, 51, 102));
        deleteBTN.setFont(new java.awt.Font("Arial Black", 1, 14)); // NOI18N
        deleteBTN.setText("Delete");
        deleteBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBTNActionPerformed(evt);
            }
        });
        getContentPane().add(deleteBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 440, 90, 50));

        Explorebtn.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        Explorebtn.setForeground(new java.awt.Color(51, 51, 255));
        Explorebtn.setText("Explore");
        Explorebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExplorebtnActionPerformed(evt);
            }
        });
        getContentPane().add(Explorebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 80, 90, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagespath/lifeonP.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 930, 1000));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTFActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        
        
        
            
        category = categoryTF.getText();
        name = nameTF.getText();
        location = locationTF.getText();
        species = speciesTF.getText();
        status = statusTF.getText();
        population = Integer.parseInt(populationTF.getText());
        
        Forest f = new Forest();
        
        f.setCategory(category);
        f.setName(name);
        f.setLocation(location);
        f.setSpecies(species);
        f.setStatus(status);
        f.setPopulation(population);
        
        //add object to Arraylist
        
        flist.add(f);
        
        count ++;
        
        
        
        displayTA.append("\nforestBTN added: " + "\n size of flist:" +flist.size());
            
            
            
        
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
         // TODO add your handling code here:
        /* category = categoryTF.getText();
         name = nameTF.getText();
         location = locationTF.getText();
         species = speciesTF.getText();
         status = statusTF.getText();
         population = (Integer.parseInt(populationTF.getText()));
         
         Forest a = new Forest();
        
        a.setCategory(category);
        a.setName(name);
        a.setLocation(location);
        a.setSpecies(species);
        a.setStatus(status);
        a.setPopulation(population);*/
        
        
        
        File outfile;
        //filewriter
        FileOutputStream fStream;
        ObjectOutputStream oStream;
        
        
        //try catch
        try{
            outfile = new File ("display.data");
            fStream= new FileOutputStream(outfile);
            oStream= new ObjectOutputStream(fStream);
            
            oStream.writeObject(flist);
            displayTA.append("\n");
            
            
            
            
        //close
        oStream.close();
        }catch(IOException e){
            System.out.println(e);
        }
        
    }//GEN-LAST:event_saveBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fs;
        ObjectInputStream os;
        
        try{
            f= new File("display.data");
            fs = new FileInputStream(f);
            os = new ObjectInputStream(fs);
            
            /*Forest x;
            x = (Forest)os.writeObject();*/
            
            ArrayList<Forest> xList;
            xList = (ArrayList<Forest>)os.readObject();
            for(Forest x:xList){
                displayTA.append(x.toString()+"\n");
            }
                os.close();
            } catch (IOException e) {
                 System.out.println(e);
            }
           catch(ClassNotFoundException ex){
               System.out.println(ex);
               
         }
        
        
        
    }//GEN-LAST:event_loadBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
         for(int i = 0; i<flist.size(); i++){
              displayTA.append("\n"+i);
                Forest f = flist.get(i);
                displayTA.append(f.toString()+"\n");
               
            }
        
        
    }//GEN-LAST:event_displayBTNActionPerformed

    private void searchBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBTNActionPerformed
        // TODO add your handling code here:
        String searchName = JOptionPane.showInputDialog(null,"Please enter the Forest you wish to search for");
        for(int i = 0; i <flist.size(); i = +i){
            if(searchName.equalsIgnoreCase(flist.get(i).getName()))
                JOptionPane.showMessageDialog(null,"Category" +flist.get(i).getCategory()+"\nLocation:"+flist.get(i).getLocation()+"\nSpecies:"+flist.get(i).getSpecies()+"\nStatut:"+flist.get(i).getStatus()+"\nPopulation"+flist.get(i).getPopulation());
             break;
            
        }
    }//GEN-LAST:event_searchBTNActionPerformed

    private void deleteBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBTNActionPerformed
        // TODO add your handling code here:
        if(nameTF.getText().equals("")||locationTF.getText().equals("")||speciesTF.getText().equals("")||statusTF.getText().equals("")||populationTF.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Please,You Must enter New Data to Delete");
        }
        else{  name = nameTF.getText();
               location = locationTF.getText();
               species = speciesTF.getText();
               status = statusTF.getText();
               population = (Integer.parseInt(populationTF.getText()));
         
                for(int i = 0; i<flist.size(); i++){
                    if(flist.get(i).getName().equals(name)&&flist.get(i).getLocation().equals(location)&&flist.get(i).getSpecies().equals(species)&&flist.get(i).getStatus().equals(status)&&flist.get(i).getPopulation()==population){
                        flist.remove(i);
                        count = count -1;
                        JOptionPane.showMessageDialog(null,"Data Deleted"+i);
                        break;
                    }
            
                    if(i==count-1){
                     JOptionPane.showMessageDialog(null,"Sorry, Data not found");
                }
                    
            }
       }   
            
    }//GEN-LAST:event_deleteBTNActionPerformed

    private void forestexpBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forestexpBTNActionPerformed
        // TODO add your handling code here:
        
       
    }//GEN-LAST:event_forestexpBTNActionPerformed

    private void ExplorebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExplorebtnActionPerformed
        // TODO add your handling code here:
         ExploreGUI myGUI = new ExploreGUI();
        myGUI.show();
        dispose();
    }//GEN-LAST:event_ExplorebtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Explorebtn;
    private javax.swing.JButton addBTN;
    private javax.swing.JLabel categoryLBL;
    private javax.swing.JTextField categoryTF;
    private javax.swing.JButton deleteBTN;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.ButtonGroup grBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton loadBTN;
    private javax.swing.JLabel locationLBL;
    private javax.swing.JTextField locationTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel populationLBL;
    private javax.swing.JTextField populationTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JButton searchBTN;
    private javax.swing.JLabel speciesLBL;
    private javax.swing.JTextField speciesTF;
    private javax.swing.JLabel statusLBL;
    private javax.swing.JTextField statusTF;
    // End of variables declaration//GEN-END:variables
}
