/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainhub.sealifeapp;
import java.awt.Toolkit;
import java.awt.event.WindowEvent;
import javax.swing.JOptionPane;

/**
 *
 * @author Ruzel
 */
public class SeaLifeGUI extends javax.swing.JFrame {

    /**
     * Creates new form SeaLifeGUI
     */
    public SeaLifeGUI() {
        initComponents();
    }
    
    //close window method. Reference:(https://www.youtube.com/watch?v=ZD6626aW54M)
    public void close(){
        WindowEvent closeWindow = new WindowEvent(this, WindowEvent.WINDOW_CLOSING);
        Toolkit.getDefaultToolkit().getSystemEventQueue().postEvent(closeWindow);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        title = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        SeaLifeAnimalsBTN = new javax.swing.JButton();
        ExitBTN = new javax.swing.JButton();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        title.setFont(new java.awt.Font("Lucida Bright", 1, 48)); // NOI18N
        title.setForeground(new java.awt.Color(51, 204, 255));
        title.setText("SEA LIFE");
        getContentPane().add(title, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 10, 220, -1));

        jTextArea1.setColumns(20);
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setText("Our planet is our home. We all co-exist \nwith other life forms. Many of these have declined due to human interference. We must value each life and prevent this decline. Life is precious and same with these endangered sea lifes.\n\n     Click the button bellow for information.");
        jTextArea1.setWrapStyleWord(true);
        jTextArea1.setOpaque(false);
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 70, 259, 140));

        SeaLifeAnimalsBTN.setBackground(new java.awt.Color(0, 135, 183));
        SeaLifeAnimalsBTN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        SeaLifeAnimalsBTN.setForeground(new java.awt.Color(255, 255, 255));
        SeaLifeAnimalsBTN.setText("Sea Life Animals");
        SeaLifeAnimalsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeaLifeAnimalsBTNActionPerformed(evt);
            }
        });
        getContentPane().add(SeaLifeAnimalsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 280, 150, 45));

        ExitBTN.setBackground(new java.awt.Color(0, 135, 183));
        ExitBTN.setForeground(new java.awt.Color(255, 255, 255));
        ExitBTN.setText("EXIT");
        ExitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(ExitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 10, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainhub/sealifeapp/sharkappimg.png"))); // NOI18N
        Background.setText("EXIT");
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SeaLifeAnimalsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeaLifeAnimalsBTNActionPerformed
        // TODO add your handling code here:
        
        SeaLifeAnimals info = new SeaLifeAnimals();
        info.setVisible(true);

        /*SeaLifeUI ui = new SeaLifeUI();
        String restart;

        do{//start do
            ui.mainMenu();
            restart = JOptionPane.showInputDialog(null, "Enter yes to go back");
        }//end do
        while(restart.equalsIgnoreCase("yes"));*/
    }//GEN-LAST:event_SeaLifeAnimalsBTNActionPerformed

    private void ExitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBTNActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_ExitBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeaLifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeaLifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeaLifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeaLifeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeaLifeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton ExitBTN;
    private javax.swing.JButton SeaLifeAnimalsBTN;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel title;
    // End of variables declaration//GEN-END:variables
}
