/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package mainhub.sealifeapp;

import javax.swing.JOptionPane;

/**
 *
 * @author Ruzel
 */
public class SeaLifeAnimals extends javax.swing.JFrame {

    /**
     * Creates new form SeaLifeAnimals
     */
    public SeaLifeAnimals() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BlueWhale = new javax.swing.JButton();
        LeatherbackTurtle = new javax.swing.JButton();
        WhiteAbalone = new javax.swing.JButton();
        Shark = new javax.swing.JButton();
        Exit = new javax.swing.JButton();
        Title = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BlueWhale.setBackground(new java.awt.Color(0, 135, 183));
        BlueWhale.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        BlueWhale.setForeground(new java.awt.Color(255, 255, 255));
        BlueWhale.setText("Blue Whale");
        BlueWhale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BlueWhaleActionPerformed(evt);
            }
        });
        getContentPane().add(BlueWhale, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 120, 60));

        LeatherbackTurtle.setBackground(new java.awt.Color(0, 135, 183));
        LeatherbackTurtle.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        LeatherbackTurtle.setForeground(new java.awt.Color(255, 255, 255));
        LeatherbackTurtle.setText("Leatherback Turtle");
        LeatherbackTurtle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LeatherbackTurtleActionPerformed(evt);
            }
        });
        getContentPane().add(LeatherbackTurtle, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, -1, 60));

        WhiteAbalone.setBackground(new java.awt.Color(0, 135, 183));
        WhiteAbalone.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        WhiteAbalone.setForeground(new java.awt.Color(255, 255, 255));
        WhiteAbalone.setText("White Abalone");
        WhiteAbalone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                WhiteAbaloneActionPerformed(evt);
            }
        });
        getContentPane().add(WhiteAbalone, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 130, 60));

        Shark.setBackground(new java.awt.Color(0, 135, 183));
        Shark.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Shark.setForeground(new java.awt.Color(255, 255, 255));
        Shark.setText("Scalloped HammerHead Shark");
        Shark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SharkActionPerformed(evt);
            }
        });
        getContentPane().add(Shark, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 90, -1, 60));

        Exit.setBackground(new java.awt.Color(0, 135, 183));
        Exit.setForeground(new java.awt.Color(255, 255, 255));
        Exit.setText("EXIT");
        Exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitActionPerformed(evt);
            }
        });
        getContentPane().add(Exit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 320, -1, -1));

        Title.setBackground(new java.awt.Color(51, 102, 255));
        Title.setFont(new java.awt.Font("Lucida Bright", 1, 36)); // NOI18N
        Title.setForeground(new java.awt.Color(51, 255, 255));
        Title.setText("SEA LIFE ANIMALS");
        getContentPane().add(Title, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mainhub/sealifeapp/sharkappimg.png"))); // NOI18N
        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 430, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BlueWhaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BlueWhaleActionPerformed
        // TODO add your handling code here:
        SeaLife ani = new SeaLife();
        ani.displayInfo1();
    }//GEN-LAST:event_BlueWhaleActionPerformed

    private void LeatherbackTurtleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LeatherbackTurtleActionPerformed
        // TODO add your handling code here:
        SeaLife ani = new SeaLife();
        ani.displayInfo2();
    }//GEN-LAST:event_LeatherbackTurtleActionPerformed

    private void WhiteAbaloneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_WhiteAbaloneActionPerformed
        // TODO add your handling code here:
        SeaLife ani = new SeaLife();
        ani.displayInfo4();
    }//GEN-LAST:event_WhiteAbaloneActionPerformed

    private void SharkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SharkActionPerformed
        // TODO add your handling code here:
        SeaLife ani = new SeaLife();
        ani.displayInfo3();
    }//GEN-LAST:event_SharkActionPerformed

    private void ExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitActionPerformed
        // TODO add your handling code here:
        int dialogResult = JOptionPane.showConfirmDialog(null, "Are you sure you want to exit?", "Exit", JOptionPane.YES_NO_OPTION);
        if (dialogResult == JOptionPane.YES_OPTION) {
            this.setVisible(false);
        }
    }//GEN-LAST:event_ExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SeaLifeAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SeaLifeAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SeaLifeAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SeaLifeAnimals.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SeaLifeAnimals().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JButton BlueWhale;
    private javax.swing.JButton Exit;
    private javax.swing.JButton LeatherbackTurtle;
    private javax.swing.JButton Shark;
    private javax.swing.JLabel Title;
    private javax.swing.JButton WhiteAbalone;
    // End of variables declaration//GEN-END:variables
}
