/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package forestapp1;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.ObjectInputStream;
import java.io.ObjectOutputStream;
import java.util.ArrayList;

/**
 *
 * @author Fred banda
 */
public class ForestGUI extends javax.swing.JFrame {
     ArrayList<Forest>flist;
     
     
     
   
    
    
   
    

    /**
     * Creates new form ForestGUI
     */
    public ForestGUI() {
        
        initComponents();
        Toolkit toolkit = getToolkit();
        Dimension size=Toolkit.getDefaultToolkit().getScreenSize();
        setLocation(size.width/2-getWidth()/2, size.height/2 - getHeight()/2);
        
        
        
        
        
        flist = new ArrayList<>();
        Forest f1 = new Forest("Forest","Amazon","Brazil","Monkeys","endagered",1236 );
        Forest f2 = new Forest("Forest","Congo Basin","DR Congo","Gorillas","endagered",658 );
        Forest f3 = new Forest("Forest","New Guinea Forest","Guinea","Green Snakes","endagered",3265 );
        Forest f4 = new Forest("Forest","Sumatra","Indonesia","Proboscis Monkeys","endagered",2341 );
       
        
        
        // show items on the form
        categoryLBL.setVisible(true);
        categoryTF.setVisible(true);
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        locationLBL.setVisible(true);
        locationTF.setVisible(true);
        speciesLBL.setVisible(true);
        speciesTF.setVisible(true);
        statusLBL.setVisible(true);
        statusTF.setVisible(true);
        populationLBL.setVisible(true);
        populationTF.setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grBTN = new javax.swing.ButtonGroup();
        categoryLBL = new javax.swing.JLabel();
        nameLBL = new javax.swing.JLabel();
        locationLBL = new javax.swing.JLabel();
        speciesLBL = new javax.swing.JLabel();
        statusLBL = new javax.swing.JLabel();
        populationLBL = new javax.swing.JLabel();
        categoryTF = new javax.swing.JTextField();
        nameTF = new javax.swing.JTextField();
        locationTF = new javax.swing.JTextField();
        speciesTF = new javax.swing.JTextField();
        statusTF = new javax.swing.JTextField();
        populationTF = new javax.swing.JTextField();
        forestBTN = new javax.swing.JRadioButton();
        animalBTN = new javax.swing.JRadioButton();
        seaBTN = new javax.swing.JRadioButton();
        jTextField1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTA = new javax.swing.JTextArea();
        loadBTN = new javax.swing.JButton();
        saveBTN = new javax.swing.JButton();
        exitBTN = new javax.swing.JButton();
        displayBTN = new javax.swing.JButton();
        addBTN = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        categoryLBL.setText("Category");
        getContentPane().add(categoryLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 122, 60, -1));

        nameLBL.setText("Name");
        getContentPane().add(nameLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 154, 45, 26));

        locationLBL.setText("Location");
        getContentPane().add(locationLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 191, 60, 22));

        speciesLBL.setText("species");
        getContentPane().add(speciesLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 220, 46, 28));

        statusLBL.setText("Status");
        getContentPane().add(statusLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 259, 46, 23));

        populationLBL.setText("Population");
        getContentPane().add(populationLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 294, -1, 22));

        categoryTF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                categoryTFActionPerformed(evt);
            }
        });
        getContentPane().add(categoryTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 119, 103, -1));
        getContentPane().add(nameTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 156, 103, -1));
        getContentPane().add(locationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 191, 103, -1));
        getContentPane().add(speciesTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 220, 103, -1));
        getContentPane().add(statusTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 260, 103, -1));
        getContentPane().add(populationTF, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 294, 103, -1));

        grBTN.add(forestBTN);
        forestBTN.setFont(new java.awt.Font("Arial Black", 1, 12)); // NOI18N
        forestBTN.setSelected(true);
        forestBTN.setText("Forest");
        forestBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                forestBTNActionPerformed(evt);
            }
        });
        getContentPane().add(forestBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 120, 98, 22));

        grBTN.add(animalBTN);
        animalBTN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        animalBTN.setText("Animal");
        animalBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                animalBTNActionPerformed(evt);
            }
        });
        getContentPane().add(animalBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 98, -1));

        grBTN.add(seaBTN);
        seaBTN.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        seaBTN.setText("Sea");
        seaBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seaBTNActionPerformed(evt);
            }
        });
        getContentPane().add(seaBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 192, 98, -1));

        jTextField1.setBackground(new java.awt.Color(204, 255, 204));
        jTextField1.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jTextField1.setText("        Life on Planet");
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 240, 60));

        displayTA.setColumns(20);
        displayTA.setFont(new java.awt.Font("Arial Black", 0, 14)); // NOI18N
        displayTA.setRows(5);
        jScrollPane1.setViewportView(displayTA);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 360, 550, 230));

        loadBTN.setBackground(new java.awt.Color(51, 153, 0));
        loadBTN.setText("LoadFile");
        loadBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadBTNActionPerformed(evt);
            }
        });
        getContentPane().add(loadBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 110, -1, 50));

        saveBTN.setBackground(new java.awt.Color(51, 153, 0));
        saveBTN.setText("SAVEFile");
        saveBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBTNActionPerformed(evt);
            }
        });
        getContentPane().add(saveBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 190, -1, 50));

        exitBTN.setBackground(new java.awt.Color(51, 153, 0));
        exitBTN.setText("EXIT");
        exitBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitBTNActionPerformed(evt);
            }
        });
        getContentPane().add(exitBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 260, 80, 50));

        displayBTN.setText("Display");
        displayBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                displayBTNActionPerformed(evt);
            }
        });
        getContentPane().add(displayBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 393, -1, 50));

        addBTN.setText("ADD");
        addBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBTNActionPerformed(evt);
            }
        });
        getContentPane().add(addBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 393, -1, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\alexb\\Desktop\\SaveOurWildlife-TO.jpg")); // NOI18N
        jLabel2.setText("backgroungLBL");
        jLabel2.setMaximumSize(new java.awt.Dimension(2100, 1080));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1520, 1010));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void categoryTFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_categoryTFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_categoryTFActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void addBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBTNActionPerformed
        // TODO add your handling code here:
        
        if(forestBTN.isSelected()){
            
        
        
        Forest f1 = new Forest();
        
        String category = categoryTF.getText();
              f1.setCategory(category);
              f1.setCategory(categoryTF.getText());
              f1.setName(nameTF.getText());
              f1.setLocation(locationTF.getText());
              f1.setStatus(statusTF.getText());
        
        flist.add(f1);
        displayTA.setText("forestBTN added: " +f1.getCategory()+ "\n size of flist:" +flist.size());
        
        categoryTF.setText("");
        nameTF.setText("");
        
        }else if(animalBTN.isSelected()){
            Forest E = new Forest();
            E.setCategory(categoryTF.getText());
            E.setName(nameTF.getText());
            E.setPopulation(Integer.parseInt(populationTF.getText()));            
            flist.add(E);
            displayTA.setText("animalBTN added:" +E.getName() +"\n size of elist:" +flist.size());
            
             }else if(seaBTN.isSelected()){
            Forest D = new Forest();
            D.setCategory(categoryTF.getText());
            D.setName(nameTF.getText());
            D.setPopulation(Integer.parseInt(populationTF.getText()));            
            flist.add(D);
            displayTA.setText("animalBTN added:" +D.getName() +"\n size of elist:" +flist.size());
            
            
            
            
        }
        
    }//GEN-LAST:event_addBTNActionPerformed

    private void exitBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitBTNActionPerformed
        // TODO add your handling code here:
        
        System.exit(0);
    }//GEN-LAST:event_exitBTNActionPerformed

    private void forestBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_forestBTNActionPerformed
        // TODO add your handling code here:
        
        categoryLBL.setVisible(true);
        categoryTF.setVisible(true);
        nameLBL.setVisible(true);
        nameTF.setVisible(true);
        locationLBL.setVisible(true);
        locationTF.setVisible(true);
        speciesLBL.setVisible(true);
        speciesTF.setVisible(true);
        statusLBL.setVisible(true);
        statusTF.setVisible(true);
        populationLBL.setVisible(true);
        populationTF.setVisible(true);
        
        
        
        
        
        
        
    }//GEN-LAST:event_forestBTNActionPerformed

    private void saveBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBTNActionPerformed
        // TODO add your handling code here:
        
        File f;
        //filewriter
        FileOutputStream fs;
        //bufferedwriter
        ObjectOutputStream os;
        //try catch
        try{
            f = new File ("log.dat");
            fs = new FileOutputStream(f,true);
            os= new ObjectOutputStream(fs);
            
            os.writeObject(flist);
            os.close();
            displayTA.setText("Forest list written to file");
        //close
        
        }catch(IOException e){
            System.out.println("Error writing to file"+e);
        }
        
    }//GEN-LAST:event_saveBTNActionPerformed

    private void loadBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadBTNActionPerformed
        // TODO add your handling code here:
        File f;
        FileInputStream fs;
        ObjectInputStream os;
        
        try{
            f= new File("log.dat");
            fs = new FileInputStream(f);
            os = new ObjectInputStream(fs);
            
            flist = (ArrayList<Forest>)os.readObject();
            //loop over arraylist
            for(int i = 0; i<flist.size(); i++){
                Forest a = flist.get(i);
                displayTA.append(a.toString()+"\n");
            }
            os.close();
        }catch(IOException e){
            System.out.println("Error reading from file"+e);
            
        }catch(ClassNotFoundException c){
            System.out.println(""+c);
        }
        
        
    }//GEN-LAST:event_loadBTNActionPerformed

    private void displayBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_displayBTNActionPerformed
        // TODO add your handling code here:
         for(int i = 0; i<flist.size(); i++){
              displayTA.append("Inside loop"+i);
                Forest b = flist.get(i);
                displayTA.append(b.toString()+"\n");
            }
        
        
    }//GEN-LAST:event_displayBTNActionPerformed

    private void animalBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_animalBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_animalBTNActionPerformed

    private void seaBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seaBTNActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seaBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForestGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ForestGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBTN;
    private javax.swing.JRadioButton animalBTN;
    private javax.swing.JLabel categoryLBL;
    private javax.swing.JTextField categoryTF;
    private javax.swing.JButton displayBTN;
    private javax.swing.JTextArea displayTA;
    private javax.swing.JButton exitBTN;
    private javax.swing.JRadioButton forestBTN;
    private javax.swing.ButtonGroup grBTN;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton loadBTN;
    private javax.swing.JLabel locationLBL;
    private javax.swing.JTextField locationTF;
    private javax.swing.JLabel nameLBL;
    private javax.swing.JTextField nameTF;
    private javax.swing.JLabel populationLBL;
    private javax.swing.JTextField populationTF;
    private javax.swing.JButton saveBTN;
    private javax.swing.JRadioButton seaBTN;
    private javax.swing.JLabel speciesLBL;
    private javax.swing.JTextField speciesTF;
    private javax.swing.JLabel statusLBL;
    private javax.swing.JTextField statusTF;
    // End of variables declaration//GEN-END:variables
}
